version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    # GPU configuration for standalone Docker
    runtime: nvidia  # Requires NVIDIA Container Toolkit
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge